# GitHub Actions CI/CD workflow for database service
name: Database CI/CD Pipeline

on:
  push:
    branches: [staging, main]
    paths:
      - 'services/database/**'
      - '.github/workflows/**'

jobs:
  # Staging environment (always runs on staging branch)
  staging:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: staging
      image_tag: staging
      port: "8005:8000"
      container_name: compta-data-app-staging

  # Production environment for staging branch (runs after staging)
  production-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [staging]
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
      image_tag: prod
      port: "8009:8000"
      container_name: compta-data-app-prod

  # Production environment for main branch (runs immediately)
  production-main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
      image_tag: prod
      port: "8009:8000"
      container_name: compta-data-app-prod