
# GitHub Actions CI/CD workflow for database service (main branch)
name: Database CI/CD Pipeline

on:
  push:
    branches:
      - staging
    paths:
      - 'services/database/**'
      - '.github/workflows/ci-cd-database.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repo owner
        id: repo_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          cd services/database
          uv sync

      - name: Run tests
        run: |
          cd services/database
          uv run pytest
        env:
          APP_ENV: ${{ vars.APP_ENV }}

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_ENV=${{ vars.APP_ENV }} \
            -t ghcr.io/${{ steps.repo_owner.outputs.owner }}/compta-data-app:staging services/database

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ steps.repo_owner.outputs.owner }}/compta-data-app:staging
